version: '3.5'

services:
  web:
    build:
      context: ./react
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    logging:
      driver: syslog
    expose:
      - '80'
    environment:
      VIRTUAL_HOST: domain.com,www.domain.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: domain.com, www.domain.com,api.domain.com
      LETSENCRYPT_EMAIL: thenickjames@gmail.com

  api:
    build:
      context: ./flask
      dockerfile: Dockerfile.prod
    expose:
      - '80'
    restart: unless-stopped
    logging:
      driver: syslog
    env_file:
      - flask/.prod.env
    environment:
      VIRTUAL_HOST: api.domain.com,www.api.domain.com
      VIRTUAL_PORT: 80


networks:
    default:
       external:
         name: nginx-proxy
