version: '3.5'

services:
  web:
   build:
     context: ./react
     dockerfile: Dockerfile
   expose:
     - '80'
   volumes:
     - ~/Projects/react_static_starter_project/react:/app
   environment:
      VIRTUAL_HOST: localhost,www.localhost
      VIRTUAL_PORT: 3000

  api:
    build:
      context: ./flask
      dockerfile: Dockerfile
    expose:
      - '80'
    volumes:
      - ~/Projects/react_static_starter_project/flask:/home/api
    env_file:
      - flask/.dev.env
    environment:
       VIRTUAL_HOST: api.localhost,www.api.localhost
       VIRTUAL_PORT: 80


networks:
    default:
       external:
         name: nginx-proxy
